version: '3.2'

services:

  nginx:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - './nginx/nginx.conf:/etc/nginx/nginx.conf:ro'

  api:
    image: alexdebril/feed-io-platform-api:latest
    links:
      - mongo
    environment:
      MONGO_HOST: mongo
    depends_on:
      - mongo

  ws:
    image: alexdebril/feed-io-api-ws:latest

  updater:
    image: alexdebril/feed-io-platform-core-updater:latest
    restart: always
    command: "./bin/console app:update -vv"
    env_file: config.env
    links:
      - mongo
      - ws

  mongo:
    image: mongo
    hostname: mongo
    environment:
      MONGO_INITDB_DATABASE: feedio_api
    volumes:
      - './data/db:/data/db'

